### ISSUE TITLE
输出貌似语法错误

### ISSUE THREAD

**Issue by HuLian21** [bjason/163MusicToSpotify#8]
File "python2.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

python版本 2.7
请问如何解决呢

**Comment by bjason** [comment]
您试一下[AlternativeMethodForPy2.py](https://github.com/bjason/163MusicToSpotify/blob/master/AlternativeMethodForPy2.py)呢？
我电脑也是python2.7 成功运行啊…

**Comment by HuLian21** [comment]
输出成功，可是。。只有一首歌

**Comment by HuLian21** [comment]
python3

**Comment by bjason** [comment]
@HuLian21 昂 什么意思 是python2还是python3
py2的话AlternativeMethodForPy2.py应该是没问题的

**Comment by jeffchrist** [comment]
同样，输出的txt只有歌单的第一首歌

**Comment by HuLian21** [comment]
是的 PY3 PY2的都可以成功，只是只有一首歌

**Comment by bjason** [comment]
python2.py和python3.py这两个是用的官方的API，最近在抽风，输出是只有一首歌的。AlternativeMethodForPy2.py换了别人的API，我个人是可以使用的，而且输出的是完整的歌单。
如果你们尝试用AlternativeMethodForPy2.py还是一样的话，如果方便可以留下你们使用的歌单ID吗？

**Comment by HuLian21** [comment]
那个AlternativeMethodForPy2.py貌似有点小问题，同样的ID， 其他脚本获取得到，这个获取不到
另外出现这个问题
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\AlternativeMethodForPy2.py", line 50, in <module>
    trackName = track["title"]
TypeError: string indices must be integers

id=128949764

**Comment by bjason** [comment]
@HuLian21 alternative那个方法是因为API更新了出的错，现在已经适配了。但是因为是第三方API，貌似太长的歌单和隐藏的播放列表是不可以获取的…我去问问API的开发者吧😊
而python2和python3两个文件只输出一首歌是因为网易云API的问题，这个暂时无解…

**Comment by fantasylidong** [comment]
无论哪个都只有一首歌

**Comment by leon332157** [comment]
@bjason 加一个随机UA就好了

**Comment by bswbatman** [comment]
要找对id，网页打开id要能显示id歌单下全部歌曲再就行尝试

能返回一首歌说明程序运行没毛病吧

完全没毛病的路过
